sudo: required
cache: pip
addons:
  apt:
    packages:
      - bedtools
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - set -e
  - ls -all
  - python setup.py install
  - ls -all #check if fast.so is created?
  - which nosetests
  - nosetests -v
